version: '3'
services:
  proxy:
    container_name: traefik.docker
    image: traefik
    command:
      - --web
      - --docker
      - --docker.domain=docker
      - --logLevel=DEBUG
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80
    networks:
      - global
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    stdin_open: true
    tty: true
    restart: always

networks:
  global:
    external: true
